---
# tasks file for vector
- name: Download repo
  become: true
# doc: https://vector.dev/docs/setup/installation/package-managers/yum/
  ansible.builtin.shell: |
    curl --proto '=https' --tlsv1.2 -sSfL https://sh.vector.dev | bash -s -- -y --prefix /usr/local
  args:
    chdir: /root/
    creates: "/usr/local/bin/vector"

- name: Ensure vector executable is available
  stat:
    path: "/usr/local/bin/vector"
  register: vector_stat

- name: Create vector service
  become: true
  ansible.builtin.template:
    src: vector.service.j2
    dest: /usr/lib/systemd/system/vector.service
    mode: "0644"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
    backup: true

- name: Create vector configuration
  become: true
  ansible.builtin.template:
    src: vector.config.j2
    dest: "{{ vector_config_dir }}/{{ vector_config_file }}"
    mode: "0644"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
